services:
  database: 
    image: 'postgres:latest'
    env_file:
      - .env
  server:
    build: ./Komplano
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./Komplano:/app
  client:
    build: ./Komplano-Client
    env_file:
      - .env
    volumes:
      - ./Komplano-Client/src:/app/src
    depends_on:
      - server
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - server


    